auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_USERNAME
images:
  # rook
  gcr.io/kaniko-project/executor:v1.8.0-debug: hellomdk/kaniko-project/executor:v1.8.0
